### ISSUE TITLE
Github Action file to publish automatically to Open VSX

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#14]
```yaml
# Controls when the workflow will run
on:
   # Weekly at 00:00 UTC
  schedule:
    - cron: '0 0 * * 0'

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          cache: 'npm'
          check-latest: true
      - run: npm install
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }} # Assumes token is stored as OPEN_VSX_TOKEN
```
